version: '{build}'
shallow_clone: true

platform: x64

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
# Makefile
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILDER: make
    LANGUAGE: cc
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    BUILDER: make
    LANGUAGE: cc
# CMake
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    BUILDER: cmake
    CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    BUILDER: cmake
    CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"

matrix:
  fast_finish: true

before_build:
  - git config --global user.email "ci@appveyor.com"
  - git config --global user.name "CI"
  - set PATH=C:\Python36-x64;%PATH%
  - bash -c "which python"
  - bash -c "python -V"
  - bash -c "python -m pip install virtualenv wheel"
  - cmake --version
  - if %BUILDER%==cmake cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -G "%CMAKE_GENERATOR%"
  - if %BUILDER%==make tools\make detect

build_script:
  - if %BUILDER%==cmake cmake --build build --config Release --target ALL_BUILD -- %MSBUILD_FLAGS%
  - if %BUILDER%==make tools\make third_party
  - if %BUILDER%==make tools\make %LANGUAGE%
  - if %BUILDER%==make tools\make test_%LANGUAGE%

test_script:
  - if %BUILDER%==cmake cmake --build build --config Release --target RUN_TESTS

